/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class maple_MapleJNI */

#ifndef _Included_maple_MapleJNI
#define _Included_maple_MapleJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     maple_MapleJNI
 * Method:    maple_connect
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_maple_MapleJNI_maple_1connect
  (JNIEnv *, jclass);

/*
 * Class:     maple_MapleJNI
 * Method:    maple_disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_maple_MapleJNI_maple_1disconnect
  (JNIEnv *, jclass);

/*
 * Class:     maple_MapleJNI
 * Method:    maple_set_capture_mode
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_maple_MapleJNI_maple_1set_1capture_1mode
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     maple_MapleJNI
 * Method:    maple_capture_image
 * Signature: (B[B)B
 */
JNIEXPORT jbyte JNICALL Java_maple_MapleJNI_maple_1capture_1image
  (JNIEnv *, jclass, jbyte, jbyteArray);

/*
 * Class:     maple_MapleJNI
 * Method:    maple_crop_image
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_maple_MapleJNI_maple_1crop_1image
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     maple_MapleJNI
 * Method:    maple_frame_rate_ctrl
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_maple_MapleJNI_maple_1frame_1rate_1ctrl
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     maple_MapleJNI
 * Method:    maple_zoom_ctrl
 * Signature: (BJB)B
 */
JNIEXPORT jbyte JNICALL Java_maple_MapleJNI_maple_1zoom_1ctrl
  (JNIEnv *, jclass, jbyte, jlong, jbyte);

/*
 * Class:     maple_MapleJNI
 * Method:    maple_freeze_mode_ctrl
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_maple_MapleJNI_maple_1freeze_1mode_1ctrl
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     maple_MapleJNI
 * Method:    maple_focus_mode_ctrl
 * Signature: (BJ)B
 */
JNIEXPORT jbyte JNICALL Java_maple_MapleJNI_maple_1focus_1mode_1ctrl
  (JNIEnv *, jclass, jbyte, jlong);

/*
 * Class:     maple_MapleJNI
 * Method:    maple_contrast_mode_ctrl
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_maple_MapleJNI_maple_1contrast_1mode_1ctrl
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     maple_MapleJNI
 * Method:    maple_text_mode_ctrl
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_maple_MapleJNI_maple_1text_1mode_1ctrl
  (JNIEnv *, jclass, jbyte);

#ifdef __cplusplus
}
#endif
#endif
